"""init

Revision ID: 1de727277b7e
Revises: 
Create Date: 2026-04-21 21:47:12.516597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de727277b7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PEACH_USER',
    sa.Column('user_code', sa.String(length=64), nullable=False, comment='用户编码'),
    sa.Column('user_name', sa.String(length=64), nullable=False, comment='用户名称'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='用户密码'),
    sa.Column('identity_code', sa.String(length=21), nullable=True, comment='身份证号'),
    sa.Column('invalidate', sa.DateTime(), nullable=True, comment='失效时间'),
    sa.Column('auth_mode', sa.String(length=20), nullable=True, comment='认证方式'),
    sa.Column('status', sa.Integer(), nullable=False, comment='用户状态 1 启用 0 禁用'),
    sa.Column('unlock_time', sa.DateTime(), nullable=True, comment='解锁时间'),
    sa.Column('menu_style', sa.String(length=20), nullable=True, comment='菜单风格'),
    sa.Column('menu_role', sa.String(length=20), nullable=True, comment='菜单角色'),
    sa.Column('mobile_phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=30), nullable=False, comment='邮箱'),
    sa.Column('is_modify', sa.Integer(), nullable=True, comment='是否修改'),
    sa.Column('password_modify_time', sa.DateTime(), nullable=True, comment='密码修改时间'),
    sa.Column('login_failed_count', sa.Integer(), nullable=False, comment='连续登录失败次数'),
    sa.Column('lock_reason', sa.String(length=128), nullable=True, comment='锁定原因'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='Primary key UUID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('modify_time', sa.DateTime(), nullable=False, comment='Modify time'),
    sa.Column('create_id', sa.String(length=32), nullable=True, comment='Create user ID'),
    sa.Column('modify_id', sa.String(length=32), nullable=True, comment='Modify user ID'),
    sa.CheckConstraint('login_failed_count >= 0', name='ck_peach_user_failed_count'),
    sa.CheckConstraint('status in (0, 1)', name='ck_peach_user_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uk_peach_user_email'),
    sa.UniqueConstraint('mobile_phone', name='uk_peach_user_mobile_phone')
    )
    op.create_index(op.f('ix_PEACH_USER_is_deleted'), 'PEACH_USER', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_PEACH_USER_user_name'), 'PEACH_USER', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PEACH_USER_user_name'), table_name='PEACH_USER')
    op.drop_index(op.f('ix_PEACH_USER_is_deleted'), table_name='PEACH_USER')
    op.drop_table('PEACH_USER')
    # ### end Alembic commands ###
